esphome:
  name: haumtagreader
  friendly_name: HaumTagReader

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable over-the-air updates.
ota:
  - platform: esphome

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

#blue flash on mqtt connection
  on_connect:
    - light.turn_on:
        id: activity_led
        brightness: 100%
        red: 0%
        green: 0%
        blue: 100%
        flash_length: 500ms
  on_message:
    topic: haum/gachaum/strike
    payload: "open"
    then:
    #green flash
      - light.turn_on:
            id: activity_led
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
            flash_length: 500ms
      - switch.turn_on: gache

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Haumtagreader Fallback Hotspot"

captive_portal:

# Enable web server
web_server:
  port: 80

i2c:
  scan: False
  frequency: 400kHz

pn532_i2c:
  id: pn532_board
  on_tag:
    then:
    - light.turn_on:
        id: activity_led
        brightness: 100%
        red: 0%
        green: 100%
        blue: 0%
        flash_length: 500ms

light:
- platform: neopixelbus
  variant: WS2812
  pin: D8
  num_leds: 1
  flash_transition_length: 500ms
  type: GRB
  id: activity_led
  name: "${friendly_name} LED"
  restore_mode: ALWAYS_OFF

switch:
  - platform: gpio
    pin: D4
    id: gache
    name: "Porte"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: gache

